services:
  backend:
    build: .
    container_name: ai-resume-builder-backend
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - mongodb
    command: ["node", "src/index.js"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('mongoose').connect(process.env.MONGODB_URI).then(()=>console.log('ok')).catch(()=>process.exit(1))\"" ]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    container_name: ai-resume-builder-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
