version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: ai-resume-builder-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      default:
        aliases:
          - mongodb

  backend:
    build: .
    container_name: ai-resume-builder-backend
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - NODE_ENV=development
    depends_on:
      - mongodb
    command: ["node", "src/index.js"]
    restart: unless-stopped

volumes:
  mongo_data:
