name: Build & push backend image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        id: build_image
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          push: false
          tags: |
            ghcr.io/${{ github.repository_owner }}/resume_lift-backend:latest
            ghcr.io/${{ github.repository_owner }}/resume_lift-backend:${{ github.sha }}
          build-args: |
            NODE_ENV=production

      - name: Trigger Render deploy (optional)
        if: ${{ secrets.RENDER_API_KEY && secrets.RENDER_SERVICE_ID }}
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          IMAGE_SHA: ghcr.io/${{ github.repository_owner }}/resume_lift-backend:${{ github.sha }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          echo "Triggering Render deploy for service $RENDER_SERVICE_ID using image $IMAGE_SHA"
          # Safer payload: include the image we just pushed and a descriptive message. Render will attempt to deploy the service.
          curl -s -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            -d "{\"image\": \"${IMAGE_SHA}\", \"message\": \"GitHub Actions deploy: ${GITHUB_SHA}\" }"
