name: PR checks

on:
  pull_request:
    branches:
      - main

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Frontend: install and build
        run: |
          cd Frontend
          npm ci
          npm run build

      - name: Backend: install dependencies
        run: |
          cd Backend
          npm ci
